"""initial_schema

Revision ID: b283287ff573
Revises: 
Create Date: 2026-02-27 22:23:18.945964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b283287ff573'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('classification', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subgroup', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('relationship_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_or_school', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role_or_program', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('linkedin_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tie_strength', sa.Integer(), nullable=False),
    sa.Column('alignment', sa.Integer(), nullable=False),
    sa.Column('influence', sa.Integer(), nullable=False),
    sa.Column('last_interaction_date', sa.Date(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('next_action', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('introduced_by_person_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['introduced_by_person_id'], ['people.person_id'], ),
    sa.PrimaryKeyConstraint('person_id')
    )
    op.create_index(op.f('ix_people_company_or_school'), 'people', ['company_or_school'], unique=False)
    op.create_index(op.f('ix_people_email'), 'people', ['email'], unique=False)
    op.create_index(op.f('ix_people_full_name'), 'people', ['full_name'], unique=False)
    op.create_index(op.f('ix_people_linkedin_url'), 'people', ['linkedin_url'], unique=False)
    op.create_index(op.f('ix_people_status'), 'people', ['status'], unique=False)
    op.create_table('actions',
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('action_timestamp', sa.DateTime(), nullable=False),
    sa.Column('action_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_person_id', sa.Integer(), nullable=True),
    sa.Column('target_name_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('context', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['target_person_id'], ['people.person_id'], ),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_index(op.f('ix_actions_action_timestamp'), 'actions', ['action_timestamp'], unique=False)
    op.create_index(op.f('ix_actions_action_type'), 'actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_actions_follow_up_date'), 'actions', ['follow_up_date'], unique=False)
    op.create_index(op.f('ix_actions_target_person_id'), 'actions', ['target_person_id'], unique=False)
    op.create_table('sources',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_text_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parsed_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.person_id'], ),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_index(op.f('ix_sources_person_id'), 'sources', ['person_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sources_person_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_actions_target_person_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_follow_up_date'), table_name='actions')
    op.drop_index(op.f('ix_actions_action_type'), table_name='actions')
    op.drop_index(op.f('ix_actions_action_timestamp'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_people_status'), table_name='people')
    op.drop_index(op.f('ix_people_linkedin_url'), table_name='people')
    op.drop_index(op.f('ix_people_full_name'), table_name='people')
    op.drop_index(op.f('ix_people_email'), table_name='people')
    op.drop_index(op.f('ix_people_company_or_school'), table_name='people')
    op.drop_table('people')
    # ### end Alembic commands ###
